"""empty message

Revision ID: cc1345773e48
Revises: e91d3a90a903
Create Date: 2018-06-14 17:08:40.510000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1345773e48'
down_revision = 'e91d3a90a903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('project', sa.Column('name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'name')
    op.drop_column('member', 'name')
    # ### end Alembic commands ###
